### ISSUE TITLE
Missing config value for runtime_dir

### ISSUE THREAD

**Issue by maxegghead** [melvinversluijs/ionic4-openalpr-sample#1]
Hi thanks for making this sample project.  I have cloned, npm installed and tried to run both on device (iPhone 6) and in browser through Chrome.  

In both, the app runs, but when I submit a picture to be interpreted, I have:

In XCode log 'Missing config value for runtime_dir'
In Chrome console, I can see that the error is being caught  with a message of 'Unexpected end of input' which then changes to 'Missing Command Error' when I step through it.  

I seem to also get the same errors when I add openalpr to my own Ionic 4 project.   

I have reviewed all files in the openALPR plugin folder but can't understand what is failing.  Thanks in advance for help

Rich

**Comment by melvinversluijs** [comment]
Hi @maxegghead,

I've just tested the application again with my own iPhone and noticed that message as well. However I am still getting results so it does not seem to be a breaking error. 

But I can see how this is confusing so I've searched for a solution. Adding the following line to the start of the plugins/cordova-plugin-openalpr/src/openalpr.conf file seems to fix the problem: `runtime_dir = ${CMAKE_INSTALL_PREFIX}/share/openalpr/runtime_data`. I'll add this to the improve iOS issue on the plugin repository: https://github.com/iMicknl/cordova-plugin-openalpr/issues/2.

While debugging issues in Cordova I mostly use the Xcode debugger instead of trying it in Chrome. Trying out Cordova plugins does not seem to work correctly in Chrome (At least in my experience).

I've also updated the master branch of this sample since it seemed that I forgot to add the needed iOS permissions to the config.xml file.

Cheers, Melvin

**Comment by maxegghead** [comment]
Hi Melvin

 

Thanks so much for coming back to me I appreciate you taking the time to write.  

 

I really want to get this working as I think it will be really useful.

 

Your line below fixed the problem for me of the missing config.

 

I now am getting a result but it takes AGES (c. 1 minute) to process and is then pretty wrong.  This is running on iPhone XR.

 

I am taking a picture of a picture of a car on screen.  In the morning I will try a photo outside of a real car.  But I noticed previously using the api then low res photos taken of pictures on my laptop screen are interpreted very quickly and accurately.  

 

So It feels like something is up but I will take a play.  Out of interest, do you find that the results when running on phone are broadly similar to the api?

 

 

Thanks 

Richard

**Comment by melvinversluijs** [comment]
Hi @maxegghead,

Sorry for the late reply, I did not have a lot of spare time for personal projects the last couple of weeks, however I did find some time to debug this issue today. I think I've fixed the issues by editing the default cameraOptions in src/app/home/home.page.ts

```
//Set default camera options.
    this.cameraOptions = {
      quality: 60,
      destinationType: this.camera.DestinationType.DATA_URL,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE,
      correctOrientation: true
    };
```

Decreasing the quality to 60 seems to speed up the process significantly, the correctOrientation param fixes the no result issue. OpenALPR still returns some rubish results (Like IIII2III etc.) But these have a much lower confidence rate than the actual license plate value, so these can be filtered out quite easily in JS. I will create a new hotfix with these changes later this week when I've also tested this on Android.

I've primarily tested this application using the photolibrary with downloaded images, this is why I did not notice this issue, my apologies for that. 

If you have any more questions feel free to ask.

Cheers,
Melvin

**Comment by maxegghead** [comment]
Hi Melvin

 

Thanks for coming back to me again.  I tried the below, and did one time manage to get a plate interpreted when I left the app for about 5 minutes.  

 

I wonder if the cameraOptions could do with restricting the picture size?  I have an iPhone XR so possibly it’s taking a huge resolution picture?  I did try using targetWidth and targetHeight but this didn’t seem to help.

 

I tried all sorts of options with previously saved photos as well but no luck. 

 

Thanks for your continued help I’m desparate to get this working!



Cheers

Rich

**Comment by melvinversluijs** [comment]
Hi @maxegghead,

Indeed, restricting the image size seems to have been the answer, unfortunately Cordova Camera does not seem to possess any proper ways of handling this. Luckily OpenALPR has a build in option we can use. I've changed the following lines in the plugins/cordova-plugin-openalpr/src/openalpr.conf file:

```conf
//From
max_detection_input_width = 4000
max_detection_input_height = 4000

//To
max_detection_input_width = 1280
max_detection_input_height = 720
```

After changing these lines I've rebuilt the ios platform. Now I no longer get any weird results nor does it take ridiculously long. Tested this on my iPhone 7.

Could you try this out on your iPhone XR? If this indeed fixes the problem I'll at this as a TODO for the cordova-plugin-openalpr repo.

Cheers,
Melvin

**Comment by maxegghead** [comment]
thanks yeah will try that tonight

Finally enough I noticed that setting and was planning to try changing it lower as my next move. 

In fact when I use the API I tend to go with 400 pixel resolution as a maximum and still get good results so I will try a variety of settings

**Comment by maxegghead** [comment]
so I couldn’t resist giving it a try just now. unfortunately it still doesn’t work it just chugs away for about three minutes then comes up with bad results. this is an iPhone 6. on iPhone XR it is also really slow and wrong results. 





I also tried feeding in a base 64 sample picture which I have used with the API with good results and this also ran really slowly

it’s really strange

**Comment by melvinversluijs** [comment]
Hi @maxegghead,

When you check your openalpr.conf file in xcode (Resources/openalpr.conf) do you see the change to the dimensions? I've just noticed that the `ionic cordova build ios` does not seem to update the conf file without you removing the ios platform first. Maybe this is your problem? I'm assuming this happens because the build command does not rebuild the plugin when it is already installed for given platform.

The application is running very smoothly for both Camera and Photolibrary on my iPhone, so I'm quite sure that changing this should do the trick. 

Personally, I've also changed my quality setting for the cameraOptions back to 80.

Hope it helps. 

Cheers,
Melvin

**Comment by maxegghead** [comment]
hmm that fits.  i was suspicious that the settings changes were taking no effect as the processing time never seemed to reduce even when i went with tiny images and very low quality

i will check shortly.

**Comment by maxegghead** [comment]
by the way do u happen to know if there is any way to use openalpr to interpet the vin number shown on the windscreen of most cars?

**Comment by maxegghead** [comment]
Partial success!

 

Yes it was the fact that the openalpr.conf file wasn’t updating when I was running build ios.   So when I manually changed it, the alpr came alive!

 

I found that setting max-image size in openalpr.conf still meant things ran slowly, perhaps the overhead of resizing a very large jpg to a smaller one is still a big performance impact.   However I added targetHeight and targetWidth to the camera options and was able to then control things this way.  

 

Interestingly it works ok-ish on my iPhone XR but still is pretty slow on my iPhone 6.   It seems sensitive to changes in the picture size but not so much the picture quality.  I also tried changing some of the openalpr settings but they didn’t make too much difference.  The one that did help is the maximum plate width and height.  Reducing this seemed to speed things a little.

 

Overall I have found the iPhone XR speed good enough but too slow to be practical on iPhone 6 (perhaps 8 to 10 seconds to process the scan).    The issue currently I have is the accuracy.  It seems to be far lower than the accuracy I get for the same picture on the api.   Not sure why this is but I think it could be a showstopper for me, it will probably be so much easier for my app to just use the api.  Is a shame as my app will be used in some locations without good phone data coverage so I’ll have to cache photos locally for later interpretation which is much worse than live but I’m not sure how to increase accuracy further currently, bigger images didn’t seem to help.

 

I’m going to take a look next at where there is a way of telling openALPR that UK plates are the format CCNN CCC   where C=letter N=number.   

 

Thanks so much for your help so far, I feel I am close but not quite there, but you have managed to help loads with this.

 

Cheers

Rich

**Comment by melvinversluijs** [comment]
Hi @maxegghead,

Nice!

The scan takes about 5-8 seconds on my iPhone as well. But this is acceptable for my case. If the scans are not accurate you might want to check out the [official openALPR repository](https://github.com/openalpr/openalpr). Getting the latest runtime_data from here might boost your accuracy (Since the ones in the openalpr cordova repo are 2 years old. They might also be able to answer your question about the vin number.

Cheers,
Melvin
